version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "7860:7860"
    volumes:
      - .:/app
      - /app/.venv
    environment:
      - ENVIRONMENT=development
    command: python ui/gradio_app.py
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7860/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  training:
    build:
      context: .
      dockerfile: Dockerfile.training
    volumes:
      - .:/app
      - /app/.venv
    environment:
      - ENVIRONMENT=development
    command: python code/train_sqlgen_t5.py
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlruns
    command: mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri /mlruns

networks:
  default:
    name: retailgenie-network
