name: retailgenie
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip=23.0
  - pytorch=2.0.0
  - torchvision
  - torchaudio
  - cpuonly
  - pip:
      - azure-ai-ml==1.12.0
      - azure-identity==1.15.0
      - azure-storage-blob==12.19.0
      - mlflow==2.8.1
      - gradio==5.29.1
      - transformers==4.51.3
      - datasets==3.6.0
      - scikit-learn==1.6.1
      - pandas==2.2.3
      - numpy==2.2.6
      - matplotlib==3.10.3
      - fastapi==0.115.12
      - uvicorn==0.34.2
      - python-multipart==0.0.20
      - pydantic==2.11.4
      - pyyaml==6.0.2
      - tqdm==4.67.1
